<a href="https://colab.research.google.com/github/SujalGodse/Advance-Analytics-using-Statistics/blob/main/Advance_Analytics_using_Statistics_Day10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)
from numpy import random
from collections import Counter
from numpy.linalg import inv
from numpy.linalg import eig
import matplotlib
from matplotlib import pyplot as plt
import seaborn as sns
import pylab
from pylab import legend
from pylab import plot, show, title, xlabel, ylabel
import scipy
from scipy import stats
from scipy.stats import binom,poisson,norm,t,expon,f
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_excel("/content/drive/MyDrive/CDAC/CDAC_DataBook.xlsx",sheet_name="faithful")
df.head()

   eruptions  waiting
0      3.600       79
1      1.800       54
2      3.333       74
3      2.283       62
4      4.533       85

In [6]:
erupt = df.eruptions
erupt

0      3.600
1      1.800
2      3.333
3      2.283
4      4.533
       ...
267    4.117
268    2.150
269    4.417
270    1.817
271    4.467
Name: eruptions, Length: 272, dtype: float64

In [8]:
xbar = np.mean(erupt)
print(xbar)
n = len(erupt)
print(n)
sd = np.std(erupt,ddof=1)
print(sd)

3.4877830882352936
272
1.1413712511052077

## 1-sample z test/ 1 sample t test

Used to check whether the difference betweent the sample mean and claim value can be ignored or not.

Used to check whether the difference betweent the sample mean and claim value is statistically significant or not

step 1:

1. H0 U >= 3.7
2. Ha U < 3.7

Step 2:

CL = 95% = 0.95
LoS = 5% = 0.05

Step 3: 1 sample z test

Step 4: TS,p-value

In [23]:
# finding TS and p-value
t = ssw.ztest(erupt,value=3.7,alternative='smaller')    # returns (TS,p-value)
t

(np.float64(-3.06646147570652), np.float64(0.0010830435959524984))

In [17]:
# compare p-value and LoS=0.05
if t[1] > 0.05:
  print("Do not Reject H0")
else:
  print("Reject H0")

Reject H0

z = (sample mean - claimed mean) / (std / n**0.5)

In [27]:
# sample z test
z = (xbar-3.7)/(sd/n**0.5)
print(z)

-3.066461475706521

In [28]:
# calculating z on normal distribution
norm.ppf(0.05)

np.float64(-1.6448536269514729)

In above case out sam_z < z (on normal curve) so claimed value is rejected

In [29]:
norm.cdf(z)

np.float64(0.001083043595952494)

In [33]:
z = (xbar-3.53)/(sd/n**0.5)    # xbar = 3.487 ,U >= 3.53
z
# sample test z > z (value on normal distribution)

np.float64(-0.6100198729369253)

In [34]:
# calculating z on normal distribution
norm.ppf(0.05)

np.float64(-1.6448536269514729)

In above case our sam_z > z (on normal distribution) so claimed value is not rejected. It is -ve still it is not rejected because in this case it comes under chance variance.

Rejection will occur when magnitude of

In [32]:
norm.cdf(z)

np.float64(0.2671895395328251)

In [36]:
t = ssw.ztest(erupt,value=3.53,alternative='smaller')
t

(np.float64(-0.6100198729369251), np.float64(0.27092432161445423))

Q. U(Meu) will not exceed 3.37
  H0

In [39]:
z = (xbar-3.37)/(sd/n**0.5)
z

np.float64(1.7019251649638614)

In [40]:
norm.ppf(0.95)    # error on right side

np.float64(1.6448536269514722)

In [41]:
t = ssw.ztest(erupt,value=3.37,alternative='larger')
t

(np.float64(1.7019251649638607), np.float64(0.044384698843295746))

In [43]:
1-norm.cdf(1.7)   #p-value

np.float64(0.044565462758543006)

In above case sample z test is greater then 1.644 and the error is on right side so it will be rejected.

But as we compare p-value with LoS then also its Reject.

In [45]:
df.head()

   eruptions  waiting
0      3.600       79
1      1.800       54
2      3.333       74
3      2.283       62
4      4.533       85

Q. min waiting time is 75 min

H0 >= 75

Ha < 75

Upper Bound = 95%

In [52]:
xbar = np.mean(df.waiting)
print(xbar)
n = len(df.waiting)
print(n)
sd = np.std(df.waiting,ddof=1)
print(sd)

70.8970588235294
272
13.594973789999393

In [53]:
z = (xbar-75)/(sd/n**0.5)
z

np.float64(-4.977386527579323)

In [54]:
norm.ppf(0.05)

np.float64(-1.6448536269514729)

In [55]:
norm.cdf(z)

np.float64(3.222427049500585e-07)

In [61]:
t = ssw.ztest(df.waiting,value=75,alternative='smaller')
t

(np.float64(-4.9773865275793225), np.float64(3.222427049500608e-07))

In [59]:
xbar + 1.645 * sd / n**0.5    # upper bound

np.float64(72.25305924622042)

#**Note : Z test will be used only for continuous data**

# Q) Practice Problems

1. A bottled water company claims that the average quantity filled in each bottle is 1 liter. A consumer rights group suspects that the company is filling less than 1 liter on average. Form the null and alternative hypotheses using the defender’s approach.

2. A university claims that the average IQ score of students admitted to a special program is 110. An education analyst believes the actual average IQ is different from 110. Form the null and alternative hypotheses using the defender’s approach.

3. A mobile battery manufacturer states that the average battery backup time is 12 hours. A customer association feels that the average backup time is lower than claimed. Form the null and alternative hypotheses using the defender’s approach.

4. A hospital administration claims that the average waiting time in the emergency department is 15 minutes. Patients believe that the waiting time is actually more than 15 minutes. Form the null and alternative hypotheses using the defender’s approach.

5. A fertilizer company claims that each bag contains an average of 50 kg fertilizer. A distributor suspects that the bags contain less than 50 kg on average. Form the null and alternative hypotheses using the defender’s approach.

6. A coaching institute advertises that the average score of its students in a competitive exam is 78 marks. A rival institute claims that the actual average is not 78 marks. Form the null and alternative hypotheses using the defender’s approach.

7. A restaurant chain claims that the average delivery time is 30 minutes. Customers believe that deliveries are taking longer than 30 minutes on average. Form the null and alternative hypotheses using the defender’s approach.

8. A cement manufacturer claims that the average compressive strength of its cement is 5000 psi. A construction engineer suspects that the actual average strength is lower. Form the null and alternative hypotheses using the defender’s approach.

9. An airline claims that the average baggage handling time is 20 minutes. Travelers suspect that the actual average handling time exceeds 20 minutes. Form the null and alternative hypotheses using the defender’s approach.

10. A pharmaceutical company claims that a vitamin tablet contains an average of 100 mg of Vitamin C. A regulatory authority suspects that the actual average content is less than 100 mg. Form the null and alternative hypotheses using the defender’s approach.

# **2 sample t test**

In [2]:
df = pd.read_excel("/content/drive/MyDrive/CDAC/CDAC_DataBook.xlsx",sheet_name="faithful")
df.head()

   eruptions  waiting
0      3.600       79
1      1.800       54
2      3.333       74
3      2.283       62
4      4.533       85

In [3]:
df1 = df.iloc[20:60]
df2 = df.iloc[120:170]

In [4]:
print(df1.shape)
print(df2.shape)

(40, 2)
(50, 2)

In [8]:
erupt1 = df1.eruptions
erupt2 = df2.eruptions

In [14]:
s1=np.mean(erupt1)
s2=np.mean(erupt2)

### The mean of erupt2 is atleast 0.12 more than the mean of erupt 1

H0: mean(erupt2) - mean(erupt1) >= 0.12

Ha: mean(erupt2) - mean(erupt1) < 0.12

In [25]:
ssw.ztest(erupt2,erupt1,value=0.12,alternative='smaller')

(np.float64(-0.3196536558502502), np.float64(0.3746154475542464))

In [22]:
sample_statistics = s2-s1
sample_statistics

np.float64(0.040189999999999504)

In [27]:
ssw.ztest(erupt2,erupt1,value=0,alternative='two-sided')

(np.float64(0.160968305082337), np.float64(0.8721183639481939))

Formula: (x2bar - x1bar) - D / ((std1^2/n1) + (std2^2/n2))**0.5

In [33]:
z = ((s2-s1)-0.12)/((np.std(erupt1,ddof=1)**2/len(erupt1)) + (np.std(erupt2,ddof=1)**2/len(erupt2)))**0.5
z

np.float64(-0.31844451421709036)

# Problem on Churn dataset

Does the age influence on exit or not

In [36]:
df11 = pd.read_csv("/content/drive/MyDrive/CDAC/6-Churn_ModellingDataSet.csv")
df11.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [38]:
df11.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [44]:
e1 = df11.Age[np.where(df11.Exited==0)[0]]
e2 = df11.Age[np.where(df11.Exited==1)[0]]
ssw.ztest(e2,e1,value=0,alternative='two-sided')

(np.float64(29.76681499437077), np.float64(1.0508082506224645e-194))