<a href="https://colab.research.google.com/github/SujalGodse/Advance-Analytics-using-Statistics/blob/main/Unsupervised_Day27.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp
import sklearn
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression


import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)
from numpy import random
from collections import Counter
from numpy.linalg import inv
from numpy.linalg import eig
import matplotlib
from matplotlib import pyplot as plt
import seaborn as sns
import pylab
from pylab import legend
from pylab import plot, show, title, xlabel, ylabel
import scipy
from scipy import stats
from scipy.stats import binom,poisson,norm,t,expon,f
from sklearn.model_selection import train_test_split

import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw

import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp

from statsmodels.discrete.discrete_model import MNLogit

from sklearn.tree import DecisionTreeClassifier

import statsmodels.stats
from statsmodels.stats.proportion import proportions_ztest

from scipy.stats import chisquare

from scipy.stats import chi2_contingency

from statsmodels.stats import rates
from statsmodels.stats.rates import test_poisson

from statsmodels.stats.rates import test_poisson_2indep

from scipy.stats import chi2

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix

In [10]:
df = pd.read_excel('/content/drive/MyDrive/CDAC/CDAC_DataBook.xlsx',sheet_name='PCA_LDA_Data')
print(df.shape)
df.head()

(2000, 7)

     X1    X2    X3   X4   X5   X6  y
0  38.1  33.0  28.2  1.1  0.6  2.5  0
1  28.0  24.3  23.4  0.5  0.3  2.3  0
2  29.6  25.0  22.5  0.7  3.2  1.6  1
3  26.1  23.6  24.7  1.3  1.6  1.5  0
4  53.7  50.1  43.4  4.0  5.1  5.3  1

In [11]:
x = df.drop(columns='y')
y = df.y

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=20)
x_train = sm.add_constant(x_train, prepend=False)

mod1 = sm.Logit(y_train,x_train).fit()
print(mod1.summary())

Optimization terminated successfully.
         Current function value: 0.378267
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:                 1600
Model:                          Logit   Df Residuals:                     1593
Method:                           MLE   Df Model:                            6
Date:                Mon, 22 Jun 2026   Pseudo R-squ.:                  0.4540
Time:                        03:51:59   Log-Likelihood:                -605.23
converged:                       True   LL-Null:                       -1108.4
Covariance Type:            nonrobust   LLR p-value:                3.889e-214
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
X1             0.0193      0.038      0.508      0.611      -0.055       0.094
X2             0.0195      0.041      0.470      0.638      -0.062       0.101
X3            -0.0487      0.042     -1.157      0.247      -0.131       0.034
X4             1.1733      0.074     15.853      0.000       1.028       1.318
X5             1.2429      0.077     16.222      0.000       1.093       1.393
X6             1.1053      0.075     14.801      0.000       0.959       1.252
const         -6.7623      0.387    -17.493      0.000      -7.520      -6.005
==============================================================================

In [23]:
df = pd.read_excel('/content/drive/MyDrive/CDAC/CDAC_DataBook.xlsx',sheet_name='PCA_LDA_Data')

x = df.drop(columns='y')
y = df.y

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=20)

In [24]:
sc1 = StandardScaler()
x_train_sc = sc1.fit_transform(x_train)
x_test_sc = sc1.transform(x_test)

In [25]:
x_train_sc = pd.DataFrame(x_train_sc,columns=x_train.columns,index=x_train.index)
x_test_sc = pd.DataFrame(x_test_sc,columns=x_test.columns,index=x_test.index)

In [26]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
x_train_pca = pca.fit_transform(x_train_sc)
x_test_pca = pca.transform(x_test_sc)

In [27]:
x_train_pca = pd.DataFrame(x_train_pca,columns=['PC1','PC2'],index=x_train.index) # follow original index
x_test_pca = pd.DataFrame(x_test_pca,columns=['PC1','PC2'],index=x_test.index)

In [28]:
x_train_pca = sm.add_constant(x_train_pca,prepend=False)
x_test_pca = sm.add_constant(x_test_pca,prepend=False)

In [30]:
mod2 = sm.Logit(y_train,x_train_pca).fit()
print(mod2.summary())

Optimization terminated successfully.
         Current function value: 0.510214
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:                 1600
Model:                          Logit   Df Residuals:                     1597
Method:                           MLE   Df Model:                            2
Date:                Mon, 22 Jun 2026   Pseudo R-squ.:                  0.2635
Time:                        04:19:48   Log-Likelihood:                -816.34
converged:                       True   LL-Null:                       -1108.4
Covariance Type:            nonrobust   LLR p-value:                1.486e-127
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
PC1           -0.0324      0.035     -0.928      0.353      -0.101       0.036
PC2            1.6483      0.089     18.569      0.000       1.474       1.822
const          0.0601      0.062      0.970      0.332      -0.061       0.181
==============================================================================

In [31]:
y_pred = mod2.predict(x_test_pca)
y_pred = (y_pred>=0.5).astype(int)
print(confusion_matrix(y_test,y_pred))

[[162  48]
 [ 56 134]]

In [32]:
(162+134)/(162+134+48+56)

0.74

In [33]:
pca_loadings = pd.DataFrame(pca.components_.T,columns=['PC1','PC2'],index=x.columns)
pca_loadings

         PC1       PC2
X1  0.577664  0.000227
X2  0.577356  0.012625
X3  0.576858  0.008081
X4 -0.012654  0.708831
X5  0.004114  0.031695
X6 -0.004603  0.704507

# **LDA (Linear Discriminant Analysis)**

In [34]:
df = pd.read_excel('/content/drive/MyDrive/CDAC/CDAC_DataBook.xlsx',sheet_name='PCA_LDA_Data')

preds = df.drop('y', axis=1)
resp = df.y

x_train, x_test, y_train, y_test = train_test_split(preds,resp,test_size=0.2, random_state=20)

sc1 = StandardScaler()

x_train_sc = sc1.fit_transform(x_train)
x_test_sc = sc1.transform(x_test)

x_train_sc = pd.DataFrame(x_train_sc, columns=x_train.columns, index=x_train.index)
x_test_sc = pd.DataFrame(x_test_sc, columns=x_test.columns, index=x_test.index)
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda = LinearDiscriminantAnalysis()


x_train_lda = lda.fit_transform(x_train_sc,y_train)
x_test_lda = lda.transform(x_test_sc)

x_train_lda = pd.DataFrame(x_train_lda, columns=['LD1'], index=x_train.index)
x_test_lda = pd.DataFrame(x_test_lda, columns=['LD1'], index=x_test.index)

x_train_lda = sm.add_constant(x_train_lda, prepend=False)
x_test_lda = sm.add_constant(x_test_lda, prepend=False)

mod3 = sm.Logit(y_train, x_train_lda).fit()
x_test_lda = sm.add_constant(x_test_lda, prepend=False)
y_pred = mod3.predict(x_test_lda)
y_pred = (y_pred>=0.5).astype(int)
print(confusion_matrix(y_test,y_pred))

Optimization terminated successfully.
         Current function value: 0.378361
         Iterations 7
[[168  42]
 [ 50 140]]